# Generated by Django 3.0.2 on 2020-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photo/'),
        ),
    ]
